spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exeschool?
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    tomcat:
      max-active: 10
      max-idle: 8
      max-wait: 10000
      min-evictable-idle-time-millis: 1000
      time-between-eviction-runs-millis: 1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

server:
  port: 8080
